/**
 * Technology Registry Data
 *
 * Central catalog of all supported technologies with metadata.
 * Organized by category per the 20-category specification.
 *
 * Icon IDs reference simple-icons v13 slugs where available.
 * Technologies without simple-icons coverage use lucide icon names.
 */

import type { TechnologyMetadata, TechnologyCategory } from "./types";

// ─── CLOUD PROVIDERS ────────────────────────────────────────────────────────

const cloudProviders: TechnologyMetadata[] = [
  {
    id: "aws",
    name: "AWS",
    aliases: ["amazon", "amazon-web-services"],
    category: "cloud",
    provider: "aws",
    c4Classification: "infrastructure",
    icon: { id: "amazonwebservices", source: "simple-icons" },
    protocols: ["HTTPS"],
    managed: true,
    website: "https://aws.amazon.com",
    description: "Amazon Web Services",
  },
  {
    id: "azure",
    name: "Azure",
    aliases: ["microsoft-azure"],
    category: "cloud",
    provider: "azure",
    c4Classification: "infrastructure",
    icon: { id: "cloud", source: "lucide" },
    protocols: ["HTTPS"],
    managed: true,
    website: "https://azure.microsoft.com",
    description: "Microsoft Azure",
  },
  {
    id: "gcp",
    name: "Google Cloud",
    aliases: ["google-cloud-platform", "gcloud"],
    category: "cloud",
    provider: "gcp",
    c4Classification: "infrastructure",
    icon: { id: "googlecloud", source: "simple-icons" },
    protocols: ["HTTPS"],
    managed: true,
    website: "https://cloud.google.com",
    description: "Google Cloud Platform",
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    aliases: ["cf"],
    category: "cloud",
    provider: "cloudflare",
    c4Classification: "infrastructure",
    icon: { id: "cloudflare", source: "simple-icons" },
    protocols: ["HTTPS", "HTTP", "DNS"],
    managed: true,
    website: "https://www.cloudflare.com",
    description: "Cloudflare edge and security platform",
  },
  {
    id: "digitalocean",
    name: "DigitalOcean",
    aliases: ["do"],
    category: "cloud",
    provider: "digitalocean",
    c4Classification: "infrastructure",
    icon: { id: "digitalocean", source: "simple-icons" },
    protocols: ["HTTPS"],
    managed: true,
    website: "https://www.digitalocean.com",
    description: "DigitalOcean cloud infrastructure",
  },
  {
    id: "heroku",
    name: "Heroku",
    aliases: [],
    category: "cloud",
    provider: "multi-cloud",
    c4Classification: "infrastructure",
    icon: { id: "heroku", source: "simple-icons" },
    protocols: ["HTTPS"],
    managed: true,
    website: "https://www.heroku.com",
    description: "Heroku platform as a service",
  },
  {
    id: "oracle",
    name: "Oracle Cloud",
    aliases: ["oci", "oracle-cloud"],
    category: "cloud",
    provider: "oracle",
    c4Classification: "infrastructure",
    icon: { id: "oracle", source: "simple-icons" },
    protocols: ["HTTPS"],
    managed: true,
    website: "https://www.oracle.com/cloud",
    description: "Oracle Cloud Infrastructure",
  },
];

// ─── AWS SERVICES ───────────────────────────────────────────────────────────

const awsServices: TechnologyMetadata[] = [
  {
    id: "amazoneks",
    name: "Amazon EKS",
    aliases: ["eks", "elastic-kubernetes-service"],
    category: "aws",
    provider: "aws",
    c4Classification: "infrastructure",
    icon: { id: "amazoneks", source: "simple-icons" },
    protocols: ["HTTPS"],
    managed: true,
    website: "https://aws.amazon.com/eks",
    description: "Amazon Elastic Kubernetes Service",
  },
  {
    id: "amazonecs",
    name: "Amazon ECS",
    aliases: ["ecs", "elastic-container-service"],
    category: "aws",
    provider: "aws",
    c4Classification: "infrastructure",
    icon: { id: "amazonecs", source: "simple-icons" },
    protocols: ["HTTPS"],
    managed: true,
    website: "https://aws.amazon.com/ecs",
    description: "Amazon Elastic Container Service",
  },
  {
    id: "awslambda",
    name: "AWS Lambda",
    aliases: ["lambda", "faas", "serverless-function"],
    category: "aws",
    provider: "aws",
    c4Classification: "component",
    icon: { id: "awslambda", source: "simple-icons" },
    protocols: ["HTTPS", "EventBridge"],
    managed: true,
    website: "https://aws.amazon.com/lambda",
    description: "AWS serverless compute",
  },
  {
    id: "amazons3",
    name: "Amazon S3",
    aliases: ["s3", "object-storage"],
    category: "aws",
    provider: "aws",
    c4Classification: "database",
    icon: { id: "amazons3", source: "simple-icons" },
    protocols: ["HTTPS"],
    managed: true,
    website: "https://aws.amazon.com/s3",
    description: "Amazon Simple Storage Service",
  },
  {
    id: "amazonrds",
    name: "Amazon RDS",
    aliases: ["rds", "relational-database-service"],
    category: "aws",
    provider: "aws",
    c4Classification: "database",
    icon: { id: "amazonrds", source: "simple-icons" },
    protocols: ["HTTPS", "SQL"],
    managed: true,
    website: "https://aws.amazon.com/rds",
    description: "Amazon Relational Database Service",
  },
  {
    id: "amazondynamodb",
    name: "Amazon DynamoDB",
    aliases: ["dynamodb", "dynamo"],
    category: "aws",
    provider: "aws",
    c4Classification: "database",
    icon: { id: "amazondynamodb", source: "simple-icons" },
    protocols: ["HTTPS"],
    managed: true,
    website: "https://aws.amazon.com/dynamodb",
    description: "Amazon DynamoDB NoSQL database",
  },
  {
    id: "amazonelasticache",
    name: "Amazon ElastiCache",
    aliases: ["elasticache"],
    category: "aws",
    provider: "aws",
    c4Classification: "cache",
    icon: { id: "amazonelasticache", source: "simple-icons" },
    protocols: ["TCP", "HTTPS"],
    managed: true,
    website: "https://aws.amazon.com/elasticache",
    description: "Amazon ElastiCache in-memory caching",
  },
  {
    id: "amazondocumentdb",
    name: "Amazon DocumentDB",
    aliases: ["documentdb"],
    category: "aws",
    provider: "aws",
    c4Classification: "database",
    icon: { id: "amazondocumentdb", source: "simple-icons" },
    protocols: ["HTTPS"],
    managed: true,
    website: "https://aws.amazon.com/documentdb",
    description: "Amazon DocumentDB MongoDB-compatible database",
  },
  {
    id: "amazonredshift",
    name: "Amazon Redshift",
    aliases: ["redshift", "data-warehouse"],
    category: "aws",
    provider: "aws",
    c4Classification: "database",
    icon: { id: "amazonredshift", source: "simple-icons" },
    protocols: ["HTTPS", "SQL"],
    managed: true,
    website: "https://aws.amazon.com/redshift",
    description: "Amazon Redshift data warehouse",
  },
  {
    id: "amazonsqs",
    name: "Amazon SQS",
    aliases: ["sqs", "simple-queue-service"],
    category: "aws",
    provider: "aws",
    c4Classification: "queue",
    icon: { id: "amazonsqs", source: "simple-icons" },
    protocols: ["HTTPS"],
    managed: true,
    website: "https://aws.amazon.com/sqs",
    description: "Amazon Simple Queue Service",
  },
  {
    id: "amazonsns",
    name: "Amazon SNS",
    aliases: ["sns", "simple-notification-service"],
    category: "aws",
    provider: "aws",
    c4Classification: "queue",
    icon: { id: "amazonsns", source: "simple-icons" },
    protocols: ["HTTPS"],
    managed: true,
    website: "https://aws.amazon.com/sns",
    description: "Amazon Simple Notification Service",
  },
  {
    id: "amazonapigateway",
    name: "Amazon API Gateway",
    aliases: ["apigateway", "aws-api-gateway"],
    category: "aws",
    provider: "aws",
    c4Classification: "container",
    icon: { id: "amazonapigateway", source: "simple-icons" },
    protocols: ["HTTPS", "REST", "HTTP"],
    managed: true,
    website: "https://aws.amazon.com/api-gateway",
    description: "Amazon API Gateway",
  },
  {
    id: "awsalb",
    name: "AWS ALB",
    aliases: ["alb", "application-load-balancer", "aws-elastic-load-balancing"],
    category: "aws",
    provider: "aws",
    c4Classification: "infrastructure",
    icon: { id: "awselasticloadbalancing", source: "simple-icons" },
    protocols: ["HTTPS", "HTTP"],
    managed: true,
    website: "https://aws.amazon.com/elasticloadbalancing",
    description: "AWS Application Load Balancer",
  },
  {
    id: "awscloudwatch",
    name: "Amazon CloudWatch",
    aliases: ["cloudwatch"],
    category: "aws",
    provider: "aws",
    c4Classification: "infrastructure",
    icon: { id: "amazoncloudwatch", source: "simple-icons" },
    protocols: ["HTTPS"],
    managed: true,
    website: "https://aws.amazon.com/cloudwatch",
    description: "Amazon CloudWatch monitoring and observability",
  },
  {
    id: "awssecretsmanager",
    name: "AWS Secrets Manager",
    aliases: ["secrets-manager", "aws-secrets"],
    category: "aws",
    provider: "aws",
    c4Classification: "infrastructure",
    icon: { id: "awssecretsmanager", source: "simple-icons" },
    protocols: ["HTTPS"],
    managed: true,
    website: "https://aws.amazon.com/secrets-manager",
    description: "AWS Secrets Manager",
  },
  {
    id: "awsiam",
    name: "AWS IAM",
    aliases: ["iam", "aws-identity"],
    category: "aws",
    provider: "aws",
    c4Classification: "infrastructure",
    icon: { id: "amazoniam", source: "simple-icons" },
    protocols: ["HTTPS"],
    managed: true,
    website: "https://aws.amazon.com/iam",
    description: "AWS Identity and Access Management",
  },
  {
    id: "awscognito",
    name: "Amazon Cognito",
    aliases: ["cognito"],
    category: "aws",
    provider: "aws",
    c4Classification: "container",
    icon: { id: "amazoncognito", source: "simple-icons" },
    protocols: ["HTTPS", "OAuth", "OIDC"],
    managed: true,
    website: "https://aws.amazon.com/cognito",
    description: "Amazon Cognito user pools and identity pools",
  },
  {
    id: "awsfargate",
    name: "AWS Fargate",
    aliases: ["fargate", "serverless-containers"],
    category: "aws",
    provider: "aws",
    c4Classification: "infrastructure",
    icon: { id: "awsfargate", source: "simple-icons" },
    protocols: ["HTTPS"],
    managed: true,
    website: "https://aws.amazon.com/fargate",
    description: "AWS Fargate serverless containers",
  },
];

// ─── AZURE SERVICES ─────────────────────────────────────────────────────────

const azureServices: TechnologyMetadata[] = [
  {
    id: "azureaks",
    name: "Azure AKS",
    aliases: ["aks", "azure-kubernetes-service"],
    category: "azure",
    provider: "azure",
    c4Classification: "infrastructure",
    icon: { id: "cloud", source: "lucide" },
    protocols: ["HTTPS"],
    managed: true,
    website: "https://azure.microsoft.com/products/kubernetes-service",
    description: "Azure Kubernetes Service",
  },
  {
    id: "azurefunctions",
    name: "Azure Functions",
    aliases: ["azure-function", "azure-faas"],
    category: "azure",
    provider: "azure",
    c4Classification: "component",
    icon: { id: "cloud", source: "lucide" },
    protocols: ["HTTPS"],
    managed: true,
    website: "https://azure.microsoft.com/products/functions",
    description: "Azure serverless compute",
  },
  {
    id: "azuredevops",
    name: "Azure DevOps",
    aliases: ["devops", "azure-pipelines"],
    category: "azure",
    provider: "azure",
    c4Classification: "infrastructure",
    icon: { id: "cloud", source: "lucide" },
    protocols: ["HTTPS"],
    managed: true,
    website: "https://azure.microsoft.com/products/devops",
    description: "Azure DevOps services",
  },
  {
    id: "azureservicebus",
    name: "Azure Service Bus",
    aliases: ["servicebus", "azure-service-bus"],
    category: "azure",
    provider: "azure",
    c4Classification: "queue",
    icon: { id: "cloud", source: "lucide" },
    protocols: ["HTTPS", "AMQP"],
    managed: true,
    website: "https://azure.microsoft.com/products/service-bus",
    description: "Azure Service Bus messaging",
  },
  {
    id: "azuremonitor",
    name: "Azure Monitor",
    aliases: ["azure-monitoring", "application-insights"],
    category: "azure",
    provider: "azure",
    c4Classification: "infrastructure",
    icon: { id: "cloud", source: "lucide" },
    protocols: ["HTTPS"],
    managed: true,
    website: "https://azure.microsoft.com/products/monitor",
    description: "Azure Monitor observability",
  },
];

// ─── GCP SERVICES ───────────────────────────────────────────────────────────

const gcpServices: TechnologyMetadata[] = [
  {
    id: "gke",
    name: "Google GKE",
    aliases: ["google-kubernetes-engine", "gcp-kubernetes"],
    category: "gcp",
    provider: "gcp",
    c4Classification: "infrastructure",
    icon: { id: "googlecloud", source: "simple-icons" },
    protocols: ["HTTPS"],
    managed: true,
    website: "https://cloud.google.com/kubernetes-engine",
    description: "Google Kubernetes Engine",
  },
  {
    id: "googlecloudrun",
    name: "Google Cloud Run",
    aliases: ["cloud-run", "gcp-cloud-run"],
    category: "gcp",
    provider: "gcp",
    c4Classification: "component",
    icon: { id: "googlecloud", source: "simple-icons" },
    protocols: ["HTTPS"],
    managed: true,
    website: "https://cloud.google.com/run",
    description: "Google Cloud Run serverless containers",
  },
  {
    id: "googlecloudfunctions",
    name: "Google Cloud Functions",
    aliases: ["cloud-functions", "gcp-faas"],
    category: "gcp",
    provider: "gcp",
    c4Classification: "component",
    icon: { id: "googlecloud", source: "simple-icons" },
    protocols: ["HTTPS"],
    managed: true,
    website: "https://cloud.google.com/functions",
    description: "Google Cloud Functions serverless compute",
  },
  {
    id: "googlepubsub",
    name: "Google Pub/Sub",
    aliases: ["pub-sub", "gcp-pubsub", "google-pubsub"],
    category: "gcp",
    provider: "gcp",
    c4Classification: "queue",
    icon: { id: "googlepubsub", source: "simple-icons" },
    protocols: ["HTTPS"],
    managed: true,
    website: "https://cloud.google.com/pubsub",
    description: "Google Cloud Pub/Sub messaging",
  },
  {
    id: "googlebigquery",
    name: "Google BigQuery",
    aliases: ["bigquery", "gcp-bigquery"],
    category: "gcp",
    provider: "gcp",
    c4Classification: "database",
    icon: { id: "googlebigquery", source: "simple-icons" },
    protocols: ["HTTPS", "SQL"],
    managed: true,
    website: "https://cloud.google.com/bigquery",
    description: "Google BigQuery data warehouse",
  },
  {
    id: "googlecloudstorage",
    name: "Google Cloud Storage",
    aliases: ["gcs", "gcp-storage", "cloud-storage"],
    category: "gcp",
    provider: "gcp",
    c4Classification: "database",
    icon: { id: "googlecloudstorage", source: "simple-icons" },
    protocols: ["HTTPS"],
    managed: true,
    website: "https://cloud.google.com/storage",
    description: "Google Cloud Storage object storage",
  },
  {
    id: "gcpmonitoring",
    name: "Google Cloud Monitoring",
    aliases: ["stackdriver", "gcp-monitoring", "cloud-monitoring"],
    category: "gcp",
    provider: "gcp",
    c4Classification: "infrastructure",
    icon: { id: "googlecloud", source: "simple-icons" },
    protocols: ["HTTPS"],
    managed: true,
    website: "https://cloud.google.com/monitoring",
    description: "Google Cloud Monitoring and Stackdriver",
  },
];

// ─── KUBERNETES ─────────────────────────────────────────────────────────────

const kubernetesTech: TechnologyMetadata[] = [
  {
    id: "kubernetes",
    name: "Kubernetes",
    aliases: ["k8s", "k3s"],
    category: "kubernetes",
    provider: "multi-cloud",
    c4Classification: "infrastructure",
    icon: { id: "kubernetes", source: "simple-icons" },
    protocols: ["HTTPS"],
    description: "Container orchestration platform",
  },
];

// ─── CONTAINERS ─────────────────────────────────────────────────────────────

const containers: TechnologyMetadata[] = [
  {
    id: "docker",
    name: "Docker",
    aliases: ["containerd", "container-runtime"],
    category: "containers",
    provider: "multi-cloud",
    c4Classification: "infrastructure",
    icon: { id: "docker", source: "simple-icons" },
    protocols: [],
    description: "Container runtime and tooling",
  },
];

// ─── FRONTEND ───────────────────────────────────────────────────────────────

const frontendTech: TechnologyMetadata[] = [
  {
    id: "react",
    name: "React",
    aliases: ["reactjs", "react-js"],
    category: "frontend",
    c4Classification: "component",
    icon: { id: "react", source: "simple-icons" },
    protocols: [],
    license: "MIT",
    website: "https://react.dev",
    description: "JavaScript UI library",
  },
  {
    id: "nextdotjs",
    name: "Next.js",
    aliases: ["next", "nextjs", "next-js"],
    category: "frontend",
    c4Classification: "component",
    icon: { id: "nextdotjs", source: "simple-icons" },
    protocols: ["HTTPS", "HTTP"],
    license: "MIT",
    website: "https://nextjs.org",
    description: "React framework for production",
  },
  {
    id: "vuedotjs",
    name: "Vue.js",
    aliases: ["vue", "vuejs", "vue-js"],
    category: "frontend",
    c4Classification: "component",
    icon: { id: "vuedotjs", source: "simple-icons" },
    protocols: [],
    license: "MIT",
    website: "https://vuejs.org",
    description: "Progressive JavaScript framework",
  },
  {
    id: "angular",
    name: "Angular",
    aliases: ["angularjs", "angular-js"],
    category: "frontend",
    c4Classification: "component",
    icon: { id: "angular", source: "simple-icons" },
    protocols: [],
    license: "MIT",
    website: "https://angular.dev",
    description: "Platform for web applications",
  },
  {
    id: "svelte",
    name: "Svelte",
    aliases: ["sveltejs", "svelte-js"],
    category: "frontend",
    c4Classification: "component",
    icon: { id: "svelte", source: "simple-icons" },
    protocols: [],
    license: "MIT",
    website: "https://svelte.dev",
    description: "Cybernetically enhanced web apps",
  },
  {
    id: "web-ui",
    name: "Web UI",
    aliases: ["frontend", "web-app", "spa", "dashboard", "web-frontend"],
    category: "frontend",
    c4Classification: "container",
    icon: { id: "monitor", source: "lucide" },
    protocols: ["HTTPS", "HTTP"],
    description: "Web-based user interface",
  },
  {
    id: "mobile-app",
    name: "Mobile App",
    aliases: ["ios", "android", "mobile", "react-native", "flutter"],
    category: "frontend",
    c4Classification: "container",
    icon: { id: "smartphone", source: "lucide" },
    protocols: ["HTTPS"],
    description: "Mobile application",
  },
  {
    id: "tailwindcss",
    name: "Tailwind CSS",
    aliases: ["tailwind", "tailwindcss"],
    category: "frontend",
    c4Classification: "component",
    icon: { id: "tailwindcss", source: "simple-icons" },
    protocols: [],
    license: "MIT",
    website: "https://tailwindcss.com",
    description: "Utility-first CSS framework",
  },
  {
    id: "vite",
    name: "Vite",
    aliases: ["vitejs"],
    category: "frontend",
    c4Classification: "infrastructure",
    icon: { id: "vite", source: "simple-icons" },
    protocols: [],
    license: "MIT",
    website: "https://vite.dev",
    description: "Next generation frontend tooling",
  },
  {
    id: "webpack",
    name: "Webpack",
    aliases: ["webpackjs"],
    category: "frontend",
    c4Classification: "infrastructure",
    icon: { id: "webpack", source: "simple-icons" },
    protocols: [],
    license: "MIT",
    website: "https://webpack.js.org",
    description: "Module bundler for JavaScript",
  },
  {
    id: "typescript",
    name: "TypeScript",
    aliases: ["ts"],
    category: "frontend",
    c4Classification: "component",
    icon: { id: "typescript", source: "simple-icons" },
    protocols: [],
    license: "Apache-2.0",
    website: "https://www.typescriptlang.org",
    description: "Typed superset of JavaScript",
  },
  {
    id: "javascript",
    name: "JavaScript",
    aliases: ["js", "ecmascript"],
    category: "frontend",
    c4Classification: "component",
    icon: { id: "javascript", source: "simple-icons" },
    protocols: [],
    license: "N/A",
    website: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    description: "High-level programming language",
  },
];

// ─── BACKEND ────────────────────────────────────────────────────────────────

const backendTech: TechnologyMetadata[] = [
  {
    id: "python",
    name: "Python",
    aliases: ["py"],
    category: "backend",
    c4Classification: "component",
    icon: { id: "python", source: "simple-icons" },
    protocols: [],
    license: "PSF",
    website: "https://www.python.org",
    description: "High-level programming language",
  },
  {
    id: "fastapi",
    name: "FastAPI",
    aliases: ["fast-api"],
    category: "backend",
    c4Classification: "component",
    icon: { id: "fastapi", source: "simple-icons" },
    protocols: ["HTTPS", "HTTP", "REST", "WebSocket"],
    license: "MIT",
    website: "https://fastapi.tiangolo.com",
    description: "Modern Python web framework for APIs",
  },
  {
    id: "flask",
    name: "Flask",
    aliases: [],
    category: "backend",
    c4Classification: "component",
    icon: { id: "flask", source: "simple-icons" },
    protocols: ["HTTPS", "HTTP", "REST"],
    license: "BSD-3-Clause",
    website: "https://flask.palletsprojects.com",
    description: "Lightweight Python web framework",
  },
  {
    id: "django",
    name: "Django",
    aliases: [],
    category: "backend",
    c4Classification: "component",
    icon: { id: "django", source: "simple-icons" },
    protocols: ["HTTPS", "HTTP", "REST"],
    license: "BSD-3-Clause",
    website: "https://www.djangoproject.com",
    description: "High-level Python web framework",
  },
  {
    id: "nodedotjs",
    name: "Node.js",
    aliases: ["node", "nodejs", "node-js"],
    category: "backend",
    c4Classification: "component",
    icon: { id: "nodedotjs", source: "simple-icons" },
    protocols: ["HTTP", "HTTPS"],
    license: "MIT",
    website: "https://nodejs.org",
    description: "JavaScript runtime built on V8",
  },
  {
    id: "express",
    name: "Express",
    aliases: ["expressjs", "express-js"],
    category: "backend",
    c4Classification: "component",
    icon: { id: "express", source: "simple-icons" },
    protocols: ["HTTP", "HTTPS", "REST"],
    license: "MIT",
    website: "https://expressjs.com",
    description: "Fast, unopinionated Node.js web framework",
  },
  {
    id: "rust",
    name: "Rust",
    aliases: ["rustlang"],
    category: "backend",
    c4Classification: "component",
    icon: { id: "rust", source: "simple-icons" },
    protocols: [],
    license: "MIT/Apache-2.0",
    website: "https://www.rust-lang.org",
    description: "Systems programming language",
  },
  {
    id: "go",
    name: "Go",
    aliases: ["golang"],
    category: "backend",
    c4Classification: "component",
    icon: { id: "go", source: "simple-icons" },
    protocols: [],
    license: "BSD-3-Clause",
    website: "https://go.dev",
    description: "Fast, compiled language for systems",
  },
  {
    id: "dotnet",
    name: ".NET",
    aliases: ["dotnet-core", "aspnet", "aspnetcore", "csharp", "dotnetcore"],
    category: "backend",
    c4Classification: "component",
    icon: { id: "dotnet", source: "simple-icons" },
    protocols: ["HTTPS", "HTTP", "gRPC"],
    license: "MIT",
    website: "https://dotnet.microsoft.com",
    description: ".NET developer platform",
  },
  {
    id: "java",
    name: "Java",
    aliases: ["jdk", "jre", "openjdk"],
    category: "backend",
    c4Classification: "component",
    icon: { id: "oracle", source: "simple-icons" },
    protocols: [],
    license: "GPL-2.0",
    website: "https://openjdk.org",
    description: "Object-oriented programming language",
  },
  {
    id: "php",
    name: "PHP",
    aliases: ["php8"],
    category: "backend",
    c4Classification: "component",
    icon: { id: "php", source: "simple-icons" },
    protocols: ["HTTP", "HTTPS"],
    license: "PHP License",
    website: "https://www.php.net",
    description: "General-purpose scripting language",
  },
  {
    id: "ruby",
    name: "Ruby",
    aliases: ["ruby-lang"],
    category: "backend",
    c4Classification: "component",
    icon: { id: "ruby", source: "simple-icons" },
    protocols: [],
    license: "Ruby License",
    website: "https://www.ruby-lang.org",
    description: "Dynamic programming language",
  },
  {
    id: "rubyonrails",
    name: "Ruby on Rails",
    aliases: ["rails", "ror"],
    category: "backend",
    c4Classification: "component",
    icon: { id: "rubyonrails", source: "simple-icons" },
    protocols: ["HTTPS", "HTTP", "REST"],
    license: "MIT",
    website: "https://rubyonrails.org",
    description: "Full-stack Ruby web framework",
  },
  {
    id: "spring",
    name: "Spring",
    aliases: ["springboot", "spring-boot", "spring-framework"],
    category: "backend",
    c4Classification: "component",
    icon: { id: "spring", source: "simple-icons" },
    protocols: ["HTTPS", "HTTP", "gRPC", "REST"],
    license: "Apache-2.0",
    website: "https://spring.io",
    description: "Java application framework",
  },
  {
    id: "graphql",
    name: "GraphQL",
    aliases: ["gql"],
    category: "backend",
    c4Classification: "component",
    icon: { id: "graphql", source: "simple-icons" },
    protocols: ["HTTPS", "HTTP", "GraphQL"],
    license: "OWFa-1.0",
    website: "https://graphql.org",
    description: "Query language for APIs",
  },
  {
    id: "grpc",
    name: "gRPC",
    aliases: ["grpc-service", "grpc-api"],
    category: "backend",
    c4Classification: "component",
    icon: { id: "code", source: "lucide" },
    protocols: ["HTTPS", "HTTP/2", "gRPC"],
    license: "Apache-2.0",
    website: "https://grpc.io",
    description: "High-performance RPC framework",
  },
  {
    id: "rest-api",
    name: "REST API",
    aliases: ["rest", "api", "http-api"],
    category: "backend",
    c4Classification: "container",
    icon: { id: "code", source: "lucide" },
    protocols: ["HTTPS", "HTTP", "REST"],
    description: "RESTful API service",
  },
];

// ─── DATABASES ──────────────────────────────────────────────────────────────

const databases: TechnologyMetadata[] = [
  {
    id: "postgresql",
    name: "PostgreSQL",
    aliases: ["postgres", "psql", "pg"],
    category: "databases",
    provider: "multi-cloud",
    c4Classification: "database",
    icon: { id: "postgresql", source: "simple-icons" },
    protocols: ["SQL", "TCP"],
    license: "PostgreSQL License",
    website: "https://www.postgresql.org",
    description: "Advanced open source SQL database",
  },
  {
    id: "mysql",
    name: "MySQL",
    aliases: ["mariadb"],
    category: "databases",
    provider: "multi-cloud",
    c4Classification: "database",
    icon: { id: "mysql", source: "simple-icons" },
    protocols: ["SQL", "TCP"],
    license: "GPL-2.0",
    website: "https://www.mysql.com",
    description: "Open source relational database",
  },
  {
    id: "mariadb",
    name: "MariaDB",
    aliases: [],
    category: "databases",
    provider: "multi-cloud",
    c4Classification: "database",
    icon: { id: "mariadb", source: "simple-icons" },
    protocols: ["SQL", "TCP"],
    license: "GPL-2.0",
    website: "https://mariadb.org",
    description: "Fork of MySQL by original developers",
  },
  {
    id: "mongodb",
    name: "MongoDB",
    aliases: ["mongo", "document-db"],
    category: "databases",
    provider: "multi-cloud",
    c4Classification: "database",
    icon: { id: "mongodb", source: "simple-icons" },
    protocols: ["MongoDB", "TCP", "HTTPS"],
    license: "SSPL",
    website: "https://www.mongodb.com",
    description: "Document-oriented NoSQL database",
  },
  {
    id: "sqlite",
    name: "SQLite",
    aliases: [],
    category: "databases",
    provider: "multi-cloud",
    c4Classification: "database",
    icon: { id: "sqlite", source: "simple-icons" },
    protocols: ["SQL"],
    license: "Public Domain",
    website: "https://www.sqlite.org",
    description: "Self-contained SQL database engine",
  },
  {
    id: "cassandra",
    name: "Cassandra",
    aliases: ["scylla", "scylladb"],
    category: "databases",
    provider: "multi-cloud",
    c4Classification: "database",
    icon: { id: "apachecassandra", source: "simple-icons" },
    protocols: ["CQL", "TCP"],
    license: "Apache-2.0",
    website: "https://cassandra.apache.org",
    description: "Distributed NoSQL wide-column store",
  },
  {
    id: "elasticsearch",
    name: "Elasticsearch",
    aliases: ["es", "elastic"],
    category: "databases",
    provider: "multi-cloud",
    c4Classification: "database",
    icon: { id: "elasticsearch", source: "simple-icons" },
    protocols: ["HTTPS", "REST"],
    license: "Elastic License 2.0",
    website: "https://www.elastic.co/elasticsearch",
    description: "Distributed search and analytics engine",
  },
  {
    id: "dynamodb",
    name: "DynamoDB",
    aliases: ["dynamo"],
    category: "databases",
    provider: "aws",
    c4Classification: "database",
    icon: { id: "amazondynamodb", source: "simple-icons" },
    protocols: ["HTTPS"],
    managed: true,
    website: "https://aws.amazon.com/dynamodb",
    description: "Amazon DynamoDB key-value database",
  },
  {
    id: "redis",
    name: "Redis",
    aliases: ["redis-cache"],
    category: "databases",
    provider: "multi-cloud",
    c4Classification: "cache",
    icon: { id: "redis", source: "simple-icons" },
    protocols: ["TCP"],
    license: "BSD-3-Clause",
    website: "https://redis.io",
    description: "In-memory data store",
  },
  {
    id: "snowflake",
    name: "Snowflake",
    aliases: ["data-warehouse", "redshift", "bigquery", "synapse"],
    category: "databases",
    provider: "multi-cloud",
    c4Classification: "database",
    icon: { id: "snowflake", source: "simple-icons" },
    protocols: ["HTTPS", "SQL"],
    managed: true,
    website: "https://www.snowflake.com",
    description: "Cloud data warehouse",
  },
  {
    id: "cockroachdb",
    name: "CockroachDB",
    aliases: ["cockroach", "crdb"],
    category: "databases",
    provider: "multi-cloud",
    c4Classification: "database",
    icon: { id: "database", source: "lucide" },
    protocols: ["SQL", "TCP", "HTTPS"],
    license: "BSL-1.1",
    website: "https://www.cockroachlabs.com",
    description: "Distributed SQL database",
  },
  {
    id: "clickhouse",
    name: "ClickHouse",
    aliases: [],
    category: "databases",
    provider: "multi-cloud",
    c4Classification: "database",
    icon: { id: "clickhouse", source: "simple-icons" },
    protocols: ["TCP", "HTTPS"],
    license: "Apache-2.0",
    website: "https://clickhouse.com",
    description: "Column-oriented OLAP database",
  },
  {
    id: "timescaledb",
    name: "TimescaleDB",
    aliases: ["timescale"],
    category: "databases",
    provider: "multi-cloud",
    c4Classification: "database",
    icon: { id: "timescale", source: "simple-icons" },
    protocols: ["SQL", "TCP"],
    license: "Apache-2.0",
    website: "https://www.timescale.com",
    description: "Time-series database on PostgreSQL",
  },
  {
    id: "memcached",
    name: "Memcached",
    aliases: ["memcache", "memcache"],
    category: "databases",
    provider: "multi-cloud",
    c4Classification: "cache",
    icon: { id: "database", source: "lucide" },
    protocols: ["TCP"],
    license: "BSD",
    website: "https://memcached.org",
    description: "High-performance distributed memory caching",
  },
];

// ─── CACHE ──────────────────────────────────────────────────────────────────
// Note: Redis and Memcached are categorized in databases for backward compatibility
// but can also be found here by resolver lookup

// ─── MESSAGING ──────────────────────────────────────────────────────────────

const messaging: TechnologyMetadata[] = [
  {
    id: "kafka",
    name: "Apache Kafka",
    aliases: ["kafka", "event-stream", "message-broker", "apachekafka"],
    category: "messaging",
    provider: "multi-cloud",
    c4Classification: "queue",
    icon: { id: "apachekafka", source: "simple-icons" },
    protocols: ["TCP", "HTTPS"],
    license: "Apache-2.0",
    website: "https://kafka.apache.org",
    description: "Distributed event streaming platform",
  },
  {
    id: "rabbitmq",
    name: "RabbitMQ",
    aliases: ["amqp", "message-queue"],
    category: "messaging",
    provider: "multi-cloud",
    c4Classification: "queue",
    icon: { id: "rabbitmq", source: "simple-icons" },
    protocols: ["AMQP", "TCP", "HTTPS"],
    license: "MPL-2.0",
    website: "https://www.rabbitmq.com",
    description: "Open source message broker",
  },
  {
    id: "nats",
    name: "NATS",
    aliases: ["natsio", "nats-io"],
    category: "messaging",
    provider: "multi-cloud",
    c4Classification: "queue",
    icon: { id: "natsdotio", source: "simple-icons" },
    protocols: ["TCP", "TLS"],
    license: "Apache-2.0",
    website: "https://nats.io",
    description: "Cloud-native messaging system",
  },
  {
    id: "pulsar",
    name: "Apache Pulsar",
    aliases: ["pulsar"],
    category: "messaging",
    provider: "multi-cloud",
    c4Classification: "queue",
    icon: { id: "apachepulsar", source: "simple-icons" },
    protocols: ["TCP", "TLS"],
    license: "Apache-2.0",
    website: "https://pulsar.apache.org",
    description: "Multi-tenant, high-performance messaging",
  },
  {
    id: "rocketmq",
    name: "Apache RocketMQ",
    aliases: ["rocketmq"],
    category: "messaging",
    provider: "multi-cloud",
    c4Classification: "queue",
    icon: { id: "apacherocketmq", source: "simple-icons" },
    protocols: ["TCP"],
    license: "Apache-2.0",
    website: "https://rocketmq.apache.org",
    description: "Distributed messaging and streaming",
  },
  {
    id: "sqs",
    name: "Amazon SQS",
    aliases: ["sqs", "simple-queue-service"],
    category: "messaging",
    provider: "aws",
    c4Classification: "queue",
    icon: { id: "amazonsqs", source: "simple-icons" },
    protocols: ["HTTPS"],
    managed: true,
    website: "https://aws.amazon.com/sqs",
    description: "Amazon Simple Queue Service",
  },
  {
    id: "sns",
    name: "Amazon SNS",
    aliases: ["sns", "simple-notification-service"],
    category: "messaging",
    provider: "aws",
    c4Classification: "queue",
    icon: { id: "amazonsns", source: "simple-icons" },
    protocols: ["HTTPS"],
    managed: true,
    website: "https://aws.amazon.com/sns",
    description: "Amazon Simple Notification Service",
  },
  {
    id: "googlepubsub-messaging",
    name: "Google Pub/Sub",
    aliases: ["pub-sub", "gcp-pubsub", "google-pubsub"],
    category: "messaging",
    provider: "gcp",
    c4Classification: "queue",
    icon: { id: "googlepubsub", source: "simple-icons" },
    protocols: ["HTTPS"],
    managed: true,
    website: "https://cloud.google.com/pubsub",
    description: "Google Cloud Pub/Sub",
    deprecated: true,
    replacement: "googlepubsub",
  },
  {
    id: "eventbridge",
    name: "EventBridge",
    aliases: ["event-bus", "aws-eventbridge"],
    category: "messaging",
    provider: "aws",
    c4Classification: "queue",
    icon: { id: "amazoneventbridge", source: "simple-icons" },
    protocols: ["HTTPS"],
    managed: true,
    website: "https://aws.amazon.com/eventbridge",
    description: "AWS serverless event bus",
  },
  {
    id: "activemq",
    name: "Apache ActiveMQ",
    aliases: ["activemq"],
    category: "messaging",
    provider: "multi-cloud",
    c4Classification: "queue",
    icon: { id: "apache", source: "simple-icons" },
    protocols: ["AMQP", "TCP", "STOMP"],
    license: "Apache-2.0",
    website: "https://activemq.apache.org",
    description: "Open source message broker",
  },
  {
    id: "flink",
    name: "Apache Flink",
    aliases: ["flink", "stream-processing"],
    category: "messaging",
    provider: "multi-cloud",
    c4Classification: "component",
    icon: { id: "apacheflink", source: "simple-icons" },
    protocols: ["TCP"],
    license: "Apache-2.0",
    website: "https://flink.apache.org",
    description: "Stream processing framework",
  },
];

// ─── API GATEWAY ────────────────────────────────────────────────────────────

const apiGateways: TechnologyMetadata[] = [
  {
    id: "kong",
    name: "Kong",
    aliases: ["kong-gateway"],
    category: "api-gateway",
    provider: "multi-cloud",
    c4Classification: "container",
    icon: { id: "kong", source: "simple-icons" },
    protocols: ["HTTPS", "HTTP", "gRPC", "REST"],
    license: "Apache-2.0",
    website: "https://konghq.com",
    description: "Cloud-native API gateway",
  },
  {
    id: "envoy",
    name: "Envoy",
    aliases: ["envoyproxy", "envoy-proxy"],
    category: "api-gateway",
    provider: "multi-cloud",
    c4Classification: "infrastructure",
    icon: { id: "envoyproxy", source: "simple-icons" },
    protocols: ["HTTPS", "HTTP", "gRPC"],
    license: "Apache-2.0",
    website: "https://www.envoyproxy.io",
    description: "Edge and service proxy",
  },
  {
    id: "nginx-ingress",
    name: "NGINX Ingress",
    aliases: ["nginx-ingress-controller"],
    category: "api-gateway",
    provider: "multi-cloud",
    c4Classification: "infrastructure",
    icon: { id: "nginx", source: "simple-icons" },
    protocols: ["HTTPS", "HTTP", "TCP"],
    license: "BSD-2-Clause",
    website: "https://www.nginx.com",
    description: "NGINX Ingress Controller for Kubernetes",
  },
  {
    id: "api-gateway",
    name: "API Gateway",
    aliases: ["gateway", "api-gw"],
    category: "api-gateway",
    provider: "multi-cloud",
    c4Classification: "container",
    icon: { id: "git-branch", source: "lucide" },
    protocols: ["HTTPS", "HTTP", "REST"],
    description: "Generic API gateway",
  },
  {
    id: "swagger",
    name: "Swagger",
    aliases: ["openapi", "openapi-swagger"],
    category: "api-gateway",
    provider: "multi-cloud",
    c4Classification: "component",
    icon: { id: "swagger", source: "simple-icons" },
    protocols: ["HTTPS", "HTTP"],
    license: "Apache-2.0",
    website: "https://swagger.io",
    description: "API description and documentation",
  },
];

// ─── LOAD BALANCING ─────────────────────────────────────────────────────────

const loadBalancers: TechnologyMetadata[] = [
  {
    id: "nginx",
    name: "NGINX",
    aliases: ["nginx-proxy", "reverse-proxy", "traefik", "haproxy", "caddy"],
    category: "load-balancing",
    provider: "multi-cloud",
    c4Classification: "infrastructure",
    icon: { id: "nginx", source: "simple-icons" },
    protocols: ["HTTPS", "HTTP", "TCP", "UDP", "TLS"],
    license: "BSD-2-Clause",
    website: "https://www.nginx.com",
    description: "Web server and reverse proxy",
  },
  {
    id: "traefik",
    name: "Traefik",
    aliases: ["traefik-proxy"],
    category: "load-balancing",
    provider: "multi-cloud",
    c4Classification: "infrastructure",
    icon: { id: "traefikproxy", source: "simple-icons" },
    protocols: ["HTTPS", "HTTP", "TCP"],
    license: "MIT",
    website: "https://traefik.io",
    description: "Cloud-native edge router",
  },
  {
    id: "haproxy",
    name: "HAProxy",
    aliases: [],
    category: "load-balancing",
    provider: "multi-cloud",
    c4Classification: "infrastructure",
    icon: { id: "loadbalancer", source: "lucide" },
    protocols: ["HTTPS", "HTTP", "TCP", "UDP"],
    license: "GPL-2.0",
    website: "https://www.haproxy.org",
    description: "High availability load balancer",
  },
  {
    id: "load-balancer",
    name: "Load Balancer",
    aliases: ["lb", "alb", "nlb", "elb"],
    category: "load-balancing",
    provider: "multi-cloud",
    c4Classification: "infrastructure",
    icon: { id: "git-merge", source: "lucide" },
    protocols: ["HTTPS", "HTTP", "TCP"],
    description: "Generic load balancer",
  },
];

// ─── AUTH / IDENTITY ────────────────────────────────────────────────────────

const authIdentity: TechnologyMetadata[] = [
  {
    id: "keycloak",
    name: "Keycloak",
    aliases: ["keycloak-sso"],
    category: "auth-identity",
    provider: "multi-cloud",
    c4Classification: "container",
    icon: { id: "keycloak", source: "simple-icons" },
    protocols: ["HTTPS", "OAuth", "OIDC", "SAML"],
    license: "Apache-2.0",
    website: "https://www.keycloak.org",
    description: "Open source identity and access management",
  },
  {
    id: "okta",
    name: "Okta",
    aliases: [],
    category: "auth-identity",
    provider: "multi-cloud",
    c4Classification: "container",
    icon: { id: "okta", source: "simple-icons" },
    protocols: ["HTTPS", "OAuth", "OIDC", "SAML"],
    managed: true,
    website: "https://www.okta.com",
    description: "Identity and access management",
  },
  {
    id: "auth0",
    name: "Auth0",
    aliases: [],
    category: "auth-identity",
    provider: "multi-cloud",
    c4Classification: "container",
    icon: { id: "auth0", source: "simple-icons" },
    protocols: ["HTTPS", "OAuth", "OIDC"],
    managed: true,
    website: "https://auth0.com",
    description: "Identity platform for developers",
  },
  {
    id: "oauth-oidc",
    name: "OAuth / OIDC",
    aliases: ["oauth2", "openid-connect", "oidc", "sso"],
    category: "auth-identity",
    c4Classification: "component",
    icon: { id: "shield", source: "lucide" },
    protocols: ["HTTPS", "OAuth", "OIDC"],
    description: "OAuth 2.0 and OpenID Connect",
  },
  {
    id: "vault",
    name: "Vault",
    aliases: ["hashicorp-vault", "secrets-manager", "secrets-vault"],
    category: "auth-identity",
    provider: "multi-cloud",
    c4Classification: "container",
    icon: { id: "vault", source: "simple-icons" },
    protocols: ["HTTPS", "TCP"],
    license: "BSL-1.1",
    website: "https://www.vaultproject.io",
    description: "HashiCorp secrets management",
  },
  {
    id: "jwt",
    name: "JWT",
    aliases: ["json-web-token", "jwt-tokens"],
    category: "auth-identity",
    c4Classification: "component",
    icon: { id: "key-round", source: "lucide" },
    protocols: ["HTTPS"],
    description: "JSON Web Token authentication",
  },
  {
    id: "rbac",
    name: "RBAC",
    aliases: ["role-based-access-control", "authorization"],
    category: "auth-identity",
    c4Classification: "component",
    icon: { id: "shield-check", source: "lucide" },
    protocols: [],
    description: "Role-based access control",
  },
];

// ─── SECURITY ───────────────────────────────────────────────────────────────

const securityTech: TechnologyMetadata[] = [
  {
    id: "cloudflare-waf",
    name: "Cloudflare WAF",
    aliases: ["waf", "web-application-firewall"],
    category: "security",
    provider: "cloudflare",
    c4Classification: "infrastructure",
    icon: { id: "cloudflare", source: "simple-icons" },
    protocols: ["HTTPS", "HTTP"],
    managed: true,
    website: "https://www.cloudflare.com/waf",
    description: "Cloudflare Web Application Firewall",
  },
  {
    id: "aws-waf",
    name: "AWS WAF",
    aliases: ["aws-waf"],
    category: "security",
    provider: "aws",
    c4Classification: "infrastructure",
    icon: { id: "shield", source: "lucide" },
    protocols: ["HTTPS"],
    managed: true,
    description: "AWS Web Application Firewall",
  },
  {
    id: "snyk",
    name: "Snyk",
    aliases: [],
    category: "security",
    provider: "multi-cloud",
    c4Classification: "infrastructure",
    icon: { id: "snyk", source: "simple-icons" },
    protocols: ["HTTPS"],
    managed: true,
    website: "https://snyk.io",
    description: "Developer-first security platform",
  },
  {
    id: "trivy",
    name: "Trivy",
    aliases: [],
    category: "security",
    provider: "multi-cloud",
    c4Classification: "infrastructure",
    icon: { id: "trivy", source: "simple-icons" },
    protocols: [],
    license: "Apache-2.0",
    website: "https://trivy.dev",
    description: "Comprehensive vulnerability scanner",
  },
  {
    id: "firewall",
    name: "Firewall",
    aliases: ["network-firewall", "security-group", "nsg"],
    category: "security",
    provider: "multi-cloud",
    c4Classification: "infrastructure",
    icon: { id: "shield-alert", source: "lucide" },
    protocols: [],
    description: "Network firewall",
  },
  {
    id: "waf",
    name: "WAF",
    aliases: ["web-application-firewall"],
    category: "security",
    provider: "multi-cloud",
    c4Classification: "infrastructure",
    icon: { id: "shield-check", source: "lucide" },
    protocols: ["HTTPS"],
    description: "Web Application Firewall",
  },
  {
    id: "kms",
    name: "KMS / Key Management",
    aliases: ["key-management", "encryption-keys", "aws-kms"],
    category: "security",
    provider: "multi-cloud",
    c4Classification: "infrastructure",
    icon: { id: "key", source: "lucide" },
    protocols: ["HTTPS"],
    description: "Key management service",
  },
  {
    id: "certificate-authority",
    name: "Certificate Authority",
    aliases: ["ca", "pki", "tls-certificates", "letsencrypt"],
    category: "security",
    provider: "multi-cloud",
    c4Classification: "infrastructure",
    icon: { id: "shield", source: "lucide" },
    protocols: ["HTTPS", "TLS"],
    description: "Certificate authority and PKI",
  },
  {
    id: "openvpn",
    name: "OpenVPN",
    aliases: ["openvpn-access-server"],
    category: "security",
    provider: "multi-cloud",
    c4Classification: "infrastructure",
    icon: { id: "openvpn", source: "simple-icons" },
    protocols: ["TCP", "UDP", "TLS"],
    license: "GPL-2.0",
    website: "https://openvpn.net",
    description: "Open source VPN solution",
  },
  {
    id: "wireguard",
    name: "WireGuard",
    aliases: [],
    category: "security",
    provider: "multi-cloud",
    c4Classification: "infrastructure",
    icon: { id: "wireguard", source: "simple-icons" },
    protocols: ["UDP"],
    license: "GPL-2.0",
    website: "https://www.wireguard.com",
    description: "Modern VPN tunnel protocol",
  },
];

// ─── OBSERVABILITY ──────────────────────────────────────────────────────────

const observability: TechnologyMetadata[] = [
  {
    id: "prometheus",
    name: "Prometheus",
    aliases: ["metrics", "monitoring"],
    category: "observability",
    provider: "multi-cloud",
    c4Classification: "container",
    icon: { id: "prometheus", source: "simple-icons" },
    protocols: ["HTTP", "HTTPS"],
    license: "Apache-2.0",
    website: "https://prometheus.io",
    description: "Open source monitoring and alerting",
  },
  {
    id: "grafana",
    name: "Grafana",
    aliases: ["dashboards", "visualization"],
    category: "observability",
    provider: "multi-cloud",
    c4Classification: "container",
    icon: { id: "grafana", source: "simple-icons" },
    protocols: ["HTTPS", "HTTP"],
    license: "AGPL-3.0",
    website: "https://grafana.com",
    description: "Open source analytics and visualization",
  },
  {
    id: "opentelemetry",
    name: "OpenTelemetry",
    aliases: ["otel", "tracing", "instrumentation"],
    category: "observability",
    provider: "multi-cloud",
    c4Classification: "component",
    icon: { id: "opentelemetry", source: "simple-icons" },
    protocols: ["HTTPS", "gRPC"],
    license: "Apache-2.0",
    website: "https://opentelemetry.io",
    description: "Observability framework and instrumentation",
  },
  {
    id: "jaeger",
    name: "Jaeger",
    aliases: ["distributed-tracing"],
    category: "observability",
    provider: "multi-cloud",
    c4Classification: "container",
    icon: { id: "jaeger", source: "simple-icons" },
    protocols: ["HTTPS", "gRPC"],
    license: "Apache-2.0",
    website: "https://www.jaegertracing.io",
    description: "Distributed tracing platform",
  },
  {
    id: "elk",
    name: "ELK Stack",
    aliases: ["elastic-stack", "logstash", "kibana"],
    category: "observability",
    provider: "multi-cloud",
    c4Classification: "container",
    icon: { id: "elasticstack", source: "simple-icons" },
    protocols: ["HTTPS", "TCP"],
    license: "Elastic License 2.0",
    website: "https://www.elastic.co/elastic-stack",
    description: "Elasticsearch, Logstash, Kibana stack",
  },
  {
    id: "kibana",
    name: "Kibana",
    aliases: [],
    category: "observability",
    provider: "multi-cloud",
    c4Classification: "container",
    icon: { id: "kibana", source: "simple-icons" },
    protocols: ["HTTPS"],
    license: "Elastic License 2.0",
    website: "https://www.elastic.co/kibana",
    description: "Kibana analytics dashboard",
  },
  {
    id: "cloudwatch",
    name: "CloudWatch",
    aliases: ["aws-cloudwatch", "aws-monitoring"],
    category: "observability",
    provider: "aws",
    c4Classification: "infrastructure",
    icon: { id: "amazoncloudwatch", source: "simple-icons" },
    protocols: ["HTTPS"],
    managed: true,
    website: "https://aws.amazon.com/cloudwatch",
    description: "Amazon CloudWatch monitoring",
  },
  {
    id: "azure-monitor",
    name: "Azure Monitor",
    aliases: ["azure-monitoring"],
    category: "observability",
    provider: "azure",
    c4Classification: "infrastructure",
    icon: { id: "cloud", source: "lucide" },
    protocols: ["HTTPS"],
    managed: true,
    description: "Azure Monitor observability",
  },
  {
    id: "gcp-monitoring",
    name: "Google Cloud Monitoring",
    aliases: ["stackdriver", "gcp-monitoring"],
    category: "observability",
    provider: "gcp",
    c4Classification: "infrastructure",
    icon: { id: "googlecloud", source: "simple-icons" },
    protocols: ["HTTPS"],
    managed: true,
    description: "Google Cloud Monitoring",
  },
  {
    id: "datadog",
    name: "Datadog",
    aliases: [],
    category: "observability",
    provider: "multi-cloud",
    c4Classification: "container",
    icon: { id: "datadog", source: "simple-icons" },
    protocols: ["HTTPS"],
    managed: true,
    website: "https://www.datadoghq.com",
    description: "Cloud monitoring and analytics",
  },
  {
    id: "newrelic",
    name: "New Relic",
    aliases: [],
    category: "observability",
    provider: "multi-cloud",
    c4Classification: "container",
    icon: { id: "newrelic", source: "simple-icons" },
    protocols: ["HTTPS"],
    managed: true,
    website: "https://newrelic.com",
    description: "Full stack observability platform",
  },
  {
    id: "splunk",
    name: "Splunk",
    aliases: [],
    category: "observability",
    provider: "multi-cloud",
    c4Classification: "container",
    icon: { id: "splunk", source: "simple-icons" },
    protocols: ["HTTPS", "TCP"],
    managed: true,
    website: "https://www.splunk.com",
    description: "Data platform for monitoring and analytics",
  },
  {
    id: "victoriametrics",
    name: "VictoriaMetrics",
    aliases: ["vm"],
    category: "observability",
    provider: "multi-cloud",
    c4Classification: "container",
    icon: { id: "victoriametrics", source: "simple-icons" },
    protocols: ["HTTPS"],
    license: "Apache-2.0",
    website: "https://victoriametrics.com",
    description: "Time-series database and monitoring",
  },
];

// ─── STORAGE ────────────────────────────────────────────────────────────────

const storageTech: TechnologyMetadata[] = [
  {
    id: "s3",
    name: "S3 / Object Storage",
    aliases: ["object-storage", "blob-storage", "minio"],
    category: "storage",
    provider: "aws",
    c4Classification: "database",
    icon: { id: "amazons3", source: "simple-icons" },
    protocols: ["HTTPS"],
    managed: true,
    website: "https://aws.amazon.com/s3",
    description: "Amazon S3 object storage",
  },
  {
    id: "cloudfront",
    name: "CloudFront",
    aliases: ["cdn", "content-delivery", "cloudflare-cdn"],
    category: "storage",
    provider: "aws",
    c4Classification: "infrastructure",
    icon: { id: "cloudflare", source: "simple-icons" },
    protocols: ["HTTPS", "HTTP"],
    managed: true,
    description: "AWS CloudFront CDN",
  },
  {
    id: "elasticsearch-storage",
    name: "Elasticsearch Storage",
    aliases: ["elasticsearch", "elastic-search"],
    category: "storage",
    provider: "multi-cloud",
    c4Classification: "database",
    icon: { id: "elasticsearch", source: "simple-icons" },
    protocols: ["HTTPS", "REST"],
    managed: false,
    description: "Elasticsearch storage backend",
  },
];

// ─── NETWORKING ─────────────────────────────────────────────────────────────

const networkingTech: TechnologyMetadata[] = [
  {
    id: "vpc",
    name: "VPC / VNet",
    aliases: ["vpc", "vnet", "virtual-network", "private-network"],
    category: "networking",
    provider: "multi-cloud",
    c4Classification: "infrastructure",
    icon: { id: "network", source: "lucide" },
    protocols: [],
    description: "Virtual private cloud / network",
  },
  {
    id: "subnet",
    name: "Subnet",
    aliases: ["sub-network"],
    category: "networking",
    provider: "multi-cloud",
    c4Classification: "infrastructure",
    icon: { id: "layers", source: "lucide" },
    protocols: [],
    description: "Network subnet",
  },
  {
    id: "nat-gateway",
    name: "NAT Gateway",
    aliases: ["nat", "nat-gw"],
    category: "networking",
    provider: "multi-cloud",
    c4Classification: "infrastructure",
    icon: { id: "globe", source: "lucide" },
    protocols: [],
    description: "Network address translation gateway",
  },
  {
    id: "internet-gateway",
    name: "Internet Gateway",
    aliases: ["igw", "internet-gw"],
    category: "networking",
    provider: "multi-cloud",
    c4Classification: "infrastructure",
    icon: { id: "globe", source: "lucide" },
    protocols: [],
    description: "Internet gateway",
  },
  {
    id: "dns",
    name: "DNS",
    aliases: ["domain-name-system", "route53", "cloudflare-dns"],
    category: "networking",
    provider: "multi-cloud",
    c4Classification: "infrastructure",
    icon: { id: "globe", source: "lucide" },
    protocols: ["DNS", "HTTPS"],
    description: "Domain Name System",
  },
  {
    id: "istio",
    name: "Istio",
    aliases: ["istio-service-mesh"],
    category: "networking",
    provider: "multi-cloud",
    c4Classification: "infrastructure",
    icon: { id: "istio", source: "simple-icons" },
    protocols: ["HTTPS", "TCP", "TLS"],
    license: "Apache-2.0",
    website: "https://istio.io",
    description: "Service mesh platform",
  },
  {
    id: "linkerd",
    name: "Linkerd",
    aliases: ["linkerd-service-mesh"],
    category: "networking",
    provider: "multi-cloud",
    c4Classification: "infrastructure",
    icon: { id: "linkerd", source: "simple-icons" },
    protocols: ["HTTPS", "TCP", "TLS"],
    license: "Apache-2.0",
    website: "https://linkerd.io",
    description: "Ultralight service mesh",
  },
];

// ─── DEVOPS / CI-CD ─────────────────────────────────────────────────────────

const devopsCicd: TechnologyMetadata[] = [
  {
    id: "terraform",
    name: "Terraform",
    aliases: ["tf", "hashicorp-terraform"],
    category: "devops-cicd",
    provider: "multi-cloud",
    c4Classification: "infrastructure",
    icon: { id: "terraform", source: "simple-icons" },
    protocols: [],
    license: "BSL-1.1",
    website: "https://www.terraform.io",
    description: "Infrastructure as code tool",
  },
  {
    id: "ansible",
    name: "Ansible",
    aliases: ["redhat-ansible"],
    category: "devops-cicd",
    provider: "multi-cloud",
    c4Classification: "infrastructure",
    icon: { id: "ansible", source: "simple-icons" },
    protocols: ["SSH", "HTTPS"],
    license: "GPL-3.0",
    website: "https://www.ansible.com",
    description: "IT automation and configuration management",
  },
  {
    id: "jenkins",
    name: "Jenkins",
    aliases: [],
    category: "devops-cicd",
    provider: "multi-cloud",
    c4Classification: "container",
    icon: { id: "jenkins", source: "simple-icons" },
    protocols: ["HTTPS"],
    license: "MIT",
    website: "https://www.jenkins.io",
    description: "Automation server for CI/CD",
  },
  {
    id: "github-actions",
    name: "GitHub Actions",
    aliases: ["gh-actions", "gha"],
    category: "devops-cicd",
    provider: "multi-cloud",
    c4Classification: "container",
    icon: { id: "githubactions", source: "simple-icons" },
    protocols: ["HTTPS"],
    website: "https://github.com/features/actions",
    description: "GitHub CI/CD automation",
  },
  {
    id: "gitlab",
    name: "GitLab",
    aliases: [],
    category: "devops-cicd",
    provider: "multi-cloud",
    c4Classification: "container",
    icon: { id: "gitlab", source: "simple-icons" },
    protocols: ["HTTPS"],
    website: "https://about.gitlab.com",
    description: "DevSecOps platform",
  },
  {
    id: "argocd",
    name: "Argo CD",
    aliases: ["argocd"],
    category: "devops-cicd",
    provider: "multi-cloud",
    c4Classification: "container",
    icon: { id: "git-branch", source: "lucide" },
    protocols: ["HTTPS"],
    license: "Apache-2.0",
    website: "https://argo-cd.readthedocs.io",
    description: "GitOps continuous delivery for Kubernetes",
  },
  {
    id: "flux",
    name: "Flux",
    aliases: ["fluxcd", "flux-cd"],
    category: "devops-cicd",
    provider: "multi-cloud",
    c4Classification: "container",
    icon: { id: "flux", source: "simple-icons" },
    protocols: ["HTTPS"],
    license: "Apache-2.0",
    website: "https://fluxcd.io",
    description: "GitOps toolkit for Kubernetes",
  },
  {
    id: "sonarqube",
    name: "SonarQube",
    aliases: [],
    category: "devops-cicd",
    provider: "multi-cloud",
    c4Classification: "container",
    icon: { id: "sonarqube", source: "simple-icons" },
    protocols: ["HTTPS"],
    license: "LGPL-3.0",
    website: "https://www.sonarsource.com/products/sonarqube",
    description: "Code quality and security analysis",
  },
];

// ─── GENERIC ARCHITECTURE COMPONENTS ────────────────────────────────────────

const genericComponents: TechnologyMetadata[] = [
  {
    id: "service",
    name: "Service",
    aliases: ["microservice", "backend-service", "api-service", "micro-service"],
    category: "generic",
    c4Classification: "component",
    icon: { id: "server", source: "lucide" },
    protocols: ["HTTPS", "HTTP"],
    description: "Backend service or microservice",
  },
  {
    id: "microservice",
    name: "Microservice",
    aliases: ["micro-service"],
    category: "generic",
    c4Classification: "component",
    icon: { id: "server", source: "lucide" },
    protocols: ["HTTPS", "HTTP"],
    description: "Microservice component",
  },
  {
    id: "worker",
    name: "Worker",
    aliases: ["background-worker", "job-processor", "consumer"],
    category: "generic",
    c4Classification: "component",
    icon: { id: "cpu", source: "lucide" },
    protocols: [],
    description: "Background worker or job processor",
  },
  {
    id: "container-generic",
    name: "Container",
    aliases: ["docker-container"],
    category: "generic",
    c4Classification: "container",
    icon: { id: "box", source: "lucide" },
    protocols: [],
    description: "Generic container workload",
  },
  {
    id: "vm",
    name: "Virtual Machine",
    aliases: ["ec2", "vm-instance", "compute-instance"],
    category: "generic",
    c4Classification: "infrastructure",
    icon: { id: "server", source: "lucide" },
    protocols: [],
    description: "Virtual machine instance",
  },
  {
    id: "serverless-function",
    name: "Serverless Function",
    aliases: ["function", "faas", "cloud-function"],
    category: "generic",
    c4Classification: "component",
    icon: { id: "zap", source: "lucide" },
    protocols: ["HTTPS"],
    description: "Serverless function / FaaS",
  },
  {
    id: "k8s-pod",
    name: "Kubernetes Pod",
    aliases: ["pod", "k8s-pod"],
    category: "generic",
    c4Classification: "container",
    icon: { id: "boxes", source: "lucide" },
    protocols: [],
    description: "Kubernetes pod",
  },
  {
    id: "k8s-deployment",
    name: "Kubernetes Deployment",
    aliases: ["deployment", "k8s-deployment"],
    category: "generic",
    c4Classification: "container",
    icon: { id: "boxes", source: "lucide" },
    protocols: [],
    description: "Kubernetes deployment",
  },
  {
    id: "bff",
    name: "BFF (Backend for Frontend)",
    aliases: ["backend-for-frontend"],
    category: "generic",
    c4Classification: "container",
    icon: { id: "server", source: "lucide" },
    protocols: ["HTTPS", "HTTP", "REST"],
    description: "Backend for Frontend pattern",
  },
  {
    id: "external-system",
    name: "External System",
    aliases: ["external", "third-party", "saas", "s3-storage"],
    category: "generic",
    c4Classification: "external-system",
    icon: { id: "globe", source: "lucide" },
    protocols: ["HTTPS"],
    description: "External or third-party system",
  },
  {
    id: "user",
    name: "User",
    aliases: ["end-user", "client", "customer"],
    category: "generic",
    c4Classification: "external-system",
    icon: { id: "user", source: "lucide" },
    protocols: ["HTTPS"],
    description: "End user or client",
  },
  {
    id: "database",
    name: "Database",
    aliases: ["db", "data-store", "datasource"],
    category: "generic",
    c4Classification: "database",
    icon: { id: "database", source: "lucide" },
    protocols: ["SQL"],
    description: "Generic database",
  },
  {
    id: "cache",
    name: "Cache",
    aliases: ["caching-layer", "in-memory-cache"],
    category: "generic",
    c4Classification: "cache",
    icon: { id: "zap", source: "lucide" },
    protocols: ["TCP"],
    description: "Generic caching layer",
  },
  {
    id: "queue",
    name: "Queue",
    aliases: ["message-queue", "job-queue"],
    category: "generic",
    c4Classification: "queue",
    icon: { id: "message-square", source: "lucide" },
    protocols: [],
    description: "Generic message queue",
  },
  {
    id: "stream",
    name: "Stream",
    aliases: ["event-stream", "data-stream", "stream-processing"],
    category: "generic",
    c4Classification: "queue",
    icon: { id: "radio", source: "lucide" },
    protocols: [],
    description: "Generic event or data stream",
  },
  {
    id: "cdn",
    name: "CDN",
    aliases: ["content-delivery-network", "edge-network"],
    category: "generic",
    c4Classification: "infrastructure",
    icon: { id: "globe", source: "lucide" },
    protocols: ["HTTPS", "HTTP"],
    description: "Content delivery network",
  },
  {
    id: "monitoring",
    name: "Monitoring",
    aliases: ["monitoring-system"],
    category: "generic",
    c4Classification: "container",
    icon: { id: "activity", source: "lucide" },
    protocols: ["HTTPS"],
    description: "Generic monitoring or observability",
  },
  {
    id: "loadbalancer",
    name: "Load Balancer",
    aliases: ["lb", "alb", "nlb", "elb", "load-balancer"],
    category: "generic",
    c4Classification: "infrastructure",
    icon: { id: "git-merge", source: "lucide" },
    protocols: ["HTTPS", "HTTP", "TCP"],
    description: "Generic load balancer",
  },
  {
    id: "gateway",
    name: "Gateway",
    aliases: ["api-gateway", "edge-gateway"],
    category: "generic",
    c4Classification: "container",
    icon: { id: "git-branch", source: "lucide" },
    protocols: ["HTTPS", "HTTP"],
    description: "Generic gateway",
  },
  {
    id: "auth",
    name: "Auth",
    aliases: ["authentication", "authorization"],
    category: "generic",
    c4Classification: "component",
    icon: { id: "shield", source: "lucide" },
    protocols: ["HTTPS"],
    description: "Authentication or authorization service",
  },
  {
    id: "secret",
    name: "Secrets Manager",
    aliases: ["secrets", "secret-store"],
    category: "generic",
    c4Classification: "container",
    icon: { id: "lock", source: "lucide" },
    protocols: ["HTTPS"],
    description: "Secrets management service",
  },
  {
    id: "search",
    name: "Search",
    aliases: ["search-engine", "full-text-search"],
    category: "generic",
    c4Classification: "container",
    icon: { id: "search", source: "lucide" },
    protocols: ["HTTPS", "REST"],
    description: "Search engine or service",
  },
  {
    id: "cron",
    name: "Cron Job",
    aliases: ["scheduler", "scheduled-task", "cron"],
    category: "generic",
    c4Classification: "component",
    icon: { id: "clock", source: "lucide" },
    protocols: [],
    description: "Scheduled job or cron task",
  },
  {
    id: "data-warehouse",
    name: "Data Warehouse",
    aliases: ["warehouse", "analytics-db"],
    category: "generic",
    c4Classification: "database",
    icon: { id: "database", source: "lucide" },
    protocols: ["HTTPS", "SQL"],
    description: "Data warehouse for analytics",
  },
  {
    id: "data-lake",
    name: "Data Lake",
    aliases: ["lake", "delta-lake"],
    category: "generic",
    c4Classification: "database",
    icon: { id: "database", source: "lucide" },
    protocols: ["HTTPS"],
    description: "Data lake for raw data storage",
  },
];

// ─── ALL TECHNOLOGIES ───────────────────────────────────────────────────────

export const technologies: TechnologyMetadata[] = [
  ...cloudProviders,
  ...awsServices,
  ...azureServices,
  ...gcpServices,
  ...kubernetesTech,
  ...containers,
  ...frontendTech,
  ...backendTech,
  ...databases,
  ...messaging,
  ...apiGateways,
  ...loadBalancers,
  ...authIdentity,
  ...securityTech,
  ...observability,
  ...storageTech,
  ...networkingTech,
  ...devopsCicd,
  ...genericComponents,
];
