/**
 * Icon Index — tree-shakeable static simple-icons map
 *
 * Imports only the simple-icons we actually use via named imports so that
 * bundlers can tree-shake the rest of the 3000+ icon library.
 *
 * Unavailable icons are omitted; the resolver falls back gracefully.
 */

import {
  siAmazon,
  siApachekafka,
  siApachepulsar,
  siApacherocketmq,
  siApachecassandra,
  siApacheflink,
  siApache,
  siAmazonapigateway,
  siAmazoncloudwatch,
  siAmazoncognito,
  siAmazondocumentdb,
  siAmazondynamodb,
  siAmazonecs,
  siAmazoneks,
  siAmazonelasticache,
  siAmazoniam,
  siAmazonrds,
  siAmazonredshift,
  siAmazons3,
  siAmazonsqs,
  siAngular,
  siAnsible,
  siAuth0,
  siAwselasticloadbalancing,
  siAwsfargate,
  siAwslambda,
  siAwssecretsmanager,
  siClickhouse,
  siCloudflare,
  siDatabricks,
  siDatadog,
  siDigitalocean,
  siDjango,
  siDocker,
  siDotnet,
  siElasticsearch,
  siExpress,
  siFastapi,
  siFlask,
  siFlux,
  siGithubactions,
  siGitlab,
  siGo,
  siGooglebigquery,
  siGooglecloud,
  siGooglecloudstorage,
  siGooglepubsub,
  siGrafana,
  siGraphql,
  siHeroku,
  siIstio,
  siJaeger,
  siJenkins,
  siJavascript,
  siKeycloak,
  siKibana,
  siKong,
  siKubernetes,
  siLinkerd,
  siMariadb,
  siMongodb,
  siMysql,
  siNatsdotio,
  siNginx,
  siNewrelic,
  siNodedotjs,
  siOkta,
  siOpentelemetry,
  siOpenvpn,
  siOracle,
  siPhp,
  siPostgresql,
  siPrometheus,
  siRabbitmq,
  siReact,
  siRedis,
  siRubyonrails,
  siRuby,
  siRust,
  siSnowflake,
  siSnyk,
  siSonarqube,
  siSplunk,
  siSpring,
  siSvelte,
  siSwagger,
  siTailwindcss,
  siTerraform,
  siTimescale,
  siTraefikproxy,
  siTrivy,
  siTypescript,
  siVault,
  siVictoriametrics,
  siVite,
  siVuedotjs,
  siWebpack,
  siWireguard,
} from "simple-icons";

export type SimpleIcon = { title: string; path: string };

function icon(value: { title: string; path: string } | undefined): SimpleIcon | null {
  if (!value || !value.path) return null;
  return { title: value.title, path: value.path };
}

/**
 * Flat map: simple-icons slug → { title, path }
 * Only includes icons we've explicitly imported (tree-shakeable).
 */
export const SIMPLE_ICON_INDEX: Record<string, SimpleIcon | null> = {
  amazon: icon(siAmazon),
  amazonapigateway: icon(siAmazonapigateway),
  amazoncloudwatch: icon(siAmazoncloudwatch),
  amazoncognito: icon(siAmazoncognito),
  amazondocumentdb: icon(siAmazondocumentdb),
  amazondynamodb: icon(siAmazondynamodb),
  amazonecs: icon(siAmazonecs),
  amazoneks: icon(siAmazoneks),
  amazonelasticache: icon(siAmazonelasticache),
  amazoniam: icon(siAmazoniam),
  amazonrds: icon(siAmazonrds),
  amazonredshift: icon(siAmazonredshift),
  amazons3: icon(siAmazons3),
  amazonsqs: icon(siAmazonsqs),
  angular: icon(siAngular),
  ansible: icon(siAnsible),
  apache: icon(siApache),
  apachecassandra: icon(siApachecassandra),
  apacheflink: icon(siApacheflink),
  apachekafka: icon(siApachekafka),
  apachepulsar: icon(siApachepulsar),
  apacherocketmq: icon(siApacherocketmq),
  auth0: icon(siAuth0),
  awselasticloadbalancing: icon(siAwselasticloadbalancing),
  awsfargate: icon(siAwsfargate),
  awslambda: icon(siAwslambda),
  awssecretsmanager: icon(siAwssecretsmanager),
  clickhouse: icon(siClickhouse),
  cloudflare: icon(siCloudflare),
  databricks: icon(siDatabricks),
  datadog: icon(siDatadog),
  digitalocean: icon(siDigitalocean),
  django: icon(siDjango),
  docker: icon(siDocker),
  dotnet: icon(siDotnet),
  elasticsearch: icon(siElasticsearch),
  express: icon(siExpress),
  fastapi: icon(siFastapi),
  flask: icon(siFlask),
  flux: icon(siFlux),
  githubactions: icon(siGithubactions),
  gitlab: icon(siGitlab),
  go: icon(siGo),
  googlebigquery: icon(siGooglebigquery),
  googlecloud: icon(siGooglecloud),
  googlecloudstorage: icon(siGooglecloudstorage),
  googlepubsub: icon(siGooglepubsub),
  grafana: icon(siGrafana),
  graphql: icon(siGraphql),
  heroku: icon(siHeroku),
  istio: icon(siIstio),
  jaeger: icon(siJaeger),
  javascript: icon(siJavascript),
  jenkins: icon(siJenkins),
  keycloak: icon(siKeycloak),
  kibana: icon(siKibana),
  kong: icon(siKong),
  kubernetes: icon(siKubernetes),
  linkerd: icon(siLinkerd),
  mariadb: icon(siMariadb),
  mongodb: icon(siMongodb),
  mysql: icon(siMysql),
  natsdotio: icon(siNatsdotio),
  nginx: icon(siNginx),
  newrelic: icon(siNewrelic),
  nodedotjs: icon(siNodedotjs),
  okta: icon(siOkta),
  opentelemetry: icon(siOpentelemetry),
  openvpn: icon(siOpenvpn),
  oracle: icon(siOracle),
  php: icon(siPhp),
  postgresql: icon(siPostgresql),
  prometheus: icon(siPrometheus),
  rabbitmq: icon(siRabbitmq),
  react: icon(siReact),
  redis: icon(siRedis),
  rubyonrails: icon(siRubyonrails),
  ruby: icon(siRuby),
  rust: icon(siRust),
  snowflake: icon(siSnowflake),
  snyk: icon(siSnyk),
  sonarqube: icon(siSonarqube),
  splunk: icon(siSplunk),
  spring: icon(siSpring),
  svelte: icon(siSvelte),
  swagger: icon(siSwagger),
  tailwindcss: icon(siTailwindcss),
  terraform: icon(siTerraform),
  timescale: icon(siTimescale),
  traefikproxy: icon(siTraefikproxy),
  trivy: icon(siTrivy),
  typescript: icon(siTypescript),
  vault: icon(siVault),
  victoriametrics: icon(siVictoriametrics),
  vite: icon(siVite),
  vuedotjs: icon(siVuedotjs),
  webpack: icon(siWebpack),
  wireguard: icon(siWireguard),
};
